run:
  path: null
globals:
  model_path: ${run.path}/best_model
  train_config_subpath: tensorboard/default/version_0
  hparams_file_name: hparams.yaml
  runs_dir_subpath: whk/code/md_with_schnet/neural_net/runs
  xtb_dir_name: xtb_md_simulations
model: 
  neighborlist:
    cutoff: ${globals.cutoff}
    dtype: float32
xtb:
  method: "gfn2-xtb" # is I think default in Turbomole
calculator:
  _target_: schnetpack.interfaces.SpkCalculator
  model_file: ${globals.model_path}
  neighbor_list:
    _target_: schnetpack.transform.ASENeighborList
    cutoff: ${model.neighborlist.cutoff}
  energy_key: ${globals.energy_key}       # comes from the train config
  force_key: ${globals.forces_key}        
  position_unit: ${data.distance_unit}
  energy_unit: ${data.property_units.energy}
  force_unit: ${data.property_units.forces}
org_data:
  _target_: schnetpack.data.AtomsDataModule
  batch_size: 100
  num_workers: 8
  pin_memory: false # just to be safe
  distance_unit: null # depends on the units used in the model
  property_units:
    energy: null 
    forces: null 
  transforms:
  - _target_: schnetpack.transform.MatScipyNeighborList
    cutoff: ${globals.cutoff}
  - _target_: schnetpack.transform.CastTo32
md:
  n_replicas: 1
  system_temperature: 300 # Kelvin
  time_step: 0.5 # fs
  n_steps: 10
  precision: 32
logger:
  buffer_size: 100
  log_every: 1
  checkpoint_every: 100
  tensorboard_props: ["energy", "temperature"]
