run:
  path: null
globals:
  model_path: ${run.path}/best_model
model: 
  neighborlist:
    cutoff: 5.0 # Angstrom
    cutoff_shell: 2.0 # Angstrom
    dtype: float32
md:
  n_replicas: 1
  system_temperature: 300 # Kelvin
  time_step: 40 # atomic units
  # time_constant: 100 # fs
  n_steps: 200
  precision: 32
logger:
  buffer_size: 100
  log_every: 1
  checkpoint_every: 100
  tensorboard_props: ["energy", "temperature"]
