name: schnarc
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - h5py
  - tensorboardX
  - pytorch
  - ase
  - numpy
  - six
  - protobuf
  - scipy
  - matplotlib
  - python-dateutil
  - pyyaml
  - tqdm
  - pyparsing
  - kiwisolver
  - cycler
  - netcdf4
  - hdf5
  - h5utils
  - jupyter
  - gfortran_linux-64
  
  # optional dependencies
  - openbabel