run:
  path: null
globals:
  model_path: ${run.path}/best_model
  train_config_subpath: tensorboard/default/version_0
  hparams_file_name: hparams.yaml
  runs_dir_subpath: whk/code/excited_state_md/training_and_inference/runs
model: 
  neighborlist:
    cutoff: ${globals.cutoff}
    dtype: float32
calculator:
  _target_: schnetpack.interfaces.SpkCalculator
  model_file: ${globals.model_path}
  neighbor_list:
    _target_: schnetpack.transform.ASENeighborList
    cutoff: ${model.neighborlist.cutoff}
  energy_key: ${globals.energy_key}       # comes from the train config
  force_key: ${globals.forces_key}        
  position_unit: ${data.distance_unit}
  energy_unit: ${data.property_units.energy}
  force_unit: ${data.property_units.forces}
org_data:
  _target_: spainn.SPAINN
  n_states: ${globals.n_states}
  n_nacs: ${globals.n_nacs}
  batch_size: 32
  num_workers: 8
  pin_memory: false # just to be safe
  distance_unit: null # depends on the units used in the model
  property_units:
    energy: null 
    forces: null 
  transforms:
  - _target_: schnetpack.transform.MatScipyNeighborList
    cutoff: ${globals.cutoff}
  - _target_: schnetpack.transform.CastTo32

