import os
import argparse
import numpy as np
import matplotlib.pyplot as plt

from hydra import initialize, compose
from omegaconf import OmegaConf, DictConfig
from schnetpack import properties
from schnetpack import units as spk_units
from schnetpack.md.data import HDF5Loader, PowerSpectrum
from ase.io import write

from md_with_schnet.utils import set_data_prefix, set_plotting_config, load_xtb_dataset
from md_with_schnet.setup_logger import setup_logger

logger = setup_logger("debug")

# Example command to run the script from within code directory:
"""
python -m md_with_schnet.neural_net.analyze_md_simulation
"""

def parse_args() -> dict:
    """ 
    Parse command-line arguments. 
    Returns:
        dict: Dictionary containing command-line arguments.
    """
    parser = argparse.ArgumentParser(description="Script for analyzing the trajectory predicted with the trained model on XTB test data.")
    # paths setup
    parser.add_argument("--trajectory_dir", type=str, default="MOTOR_MD_XTB/T300_1", help="Directory containing the trajectory data generated by Turbomole (default: MOTOR_MD_XTB/T300_1)")
    parser.add_argument("-mdir", "--model_dir", type=str, default="MOTOR_MD_XTB_T300_1_epochs_1000_bs_100_lr_0.0001_seed_42", help="Directory of the trained model (default: MOTOR_MD_XTB_T300_1_epochs_1000_bs_100_lr_0.0001_seed_42)")
    parser.add_argument("-sn", "--simulation_name", type=str, default="md_sim_steps_2000_time_step_0.5_seed_42", help="Name of the MD simulation (default: md_sim_steps_2000_time_step_0.5_seed_42)")
    return vars(parser.parse_args())

def plot_energies_system_vs_calculator(data: HDF5Loader, energies_system: np.ndarray, energies_calculator: np.ndarray):
    """ Plot the energies of the system and the calculator.
    Args:
        data (HDF5Loader): HDF5Loader object containing the MD simulation data.
        energies_system (np.ndarray): Energies of the system.
        energies_calculator (np.ndarray): Energies of the calculator.
    """
    # Get the time axis in femtoseconds
    time_axis = np.arange(data.entries) * data.time_step / spk_units.fs 

    set_plotting_config()
    plt.figure()
    plt.plot(time_axis, energies_system, label=r"E$_\mathrm{pot}$ (System)")
    plt.plot(time_axis, energies_calculator, label=r"E$_\mathrm{pot}$ (Logger)", ls="--")
    plt.ylabel("E [Hartree]")
    plt.xlabel("t [fs]")
    plt.xlim(9800,10000)
    plt.legend()
    plt.tight_layout()
    plt.show()

def plot_energies(data: HDF5Loader, true_energies: np.ndarray, predicted_energies: np.ndarray):
    """ Plot the energies of the system and the calculator.
    Args:
        data (HDF5Loader): HDF5Loader object containing the MD simulation data.
        true_energies (np.ndarray): Energies of the calculator.
        predicted_energies (np.ndarray): Energies of the system.
    """
    # Get the time axis in femtoseconds
    time_axis = np.arange(data.entries) * data.time_step / spk_units.fs 
    time_axis = time_axis[:len(true_energies)]
    predicted_energies = predicted_energies[:len(true_energies)]

    set_plotting_config()
    plt.figure()
    
    # Plot true energies
    ax1 = plt.gca()
    line1, = ax1.plot(time_axis, true_energies, label=r"True $E_\mathrm{pot}$", color='tab:orange')
    ax1.set_ylabel("E [Hartree]", color='tab:orange')
    ax1.tick_params(axis='y', labelcolor='tab:orange')

    # Plot predicted energies on the twin axis
    ax2 = ax1.twinx()
    line2, = ax2.plot(time_axis, predicted_energies, label=r"Predicted $E_\mathrm{pot}$", color='tab:blue')
    ax2.set_ylabel("E [Hartree]", color='tab:blue')
    ax2.tick_params(axis='y', labelcolor='tab:blue')

    ax1.set_xlabel("Time [fs]")

    # Create a combined legend
    lines = [line1, line2]
    labels = [line.get_label() for line in lines]
    ax1.legend(lines, labels, loc='upper right')

    #plt.legend()
    plt.tight_layout()
    plt.show()

def plot_temperature(data: HDF5Loader):
    """ Plot the temperature of the system.
    Args:
        data (HDF5Loader): HDF5Loader object containing the MD simulation data.
    """
    set_plotting_config()

    # Read the temperature
    temperature = data.get_temperature()

    # Compute the cumulative mean
    temperature_mean = np.cumsum(temperature) / (np.arange(data.entries)+1)

    # Get the time axis
    time_axis = np.arange(data.entries) * data.time_step / spk_units.fs  # in fs

    plt.figure(figsize=(8,4))
    plt.plot(time_axis, temperature, label='T')
    plt.plot(time_axis, temperature_mean, label='T (avg.)')
    plt.ylabel('T [K]')
    plt.xlabel('t [fs]')
    plt.legend()
    plt.tight_layout()
    plt.show()

def plot_spectrum(frequencies: np.ndarray, intensities: np.ndarray):
    """ Plot the spectrum.
    Args:
        frequencies (np.ndarray): Frequencies of the spectrum.
        intensities (np.ndarray): Intensities of the spectrum.
    """
    set_plotting_config()
    # Plot the spectrum
    plt.figure()
    plt.plot(frequencies, intensities)
    plt.xlim(0,4000)
    plt.ylim(0,100)
    plt.ylabel('I [a.u.]')
    plt.xlabel(r'$\omega$ [cm$^{-1}$]')
    plt.show()

def main(trajectory_dir: str, model_dir: str, simulation_name: str):
    ####################### 1) Compose the config ###########################
    with initialize(config_path="conf", job_name="inference"):
        cfg: DictConfig = compose(config_name="inference_config")
    logger.info(f"Loaded config:\n{OmegaConf.to_yaml(cfg)}")

    ####################### 2) Prepare Data and Paths #########################
    md_workdir = cfg.run.path

    # load the HDF5 file containing the MD simulation data
    log_file = os.path.join(md_workdir, "simulation_schnet.hdf5")
    data = HDF5Loader(log_file)

    # log available properties
    log_properties = [prop for prop in data.properties]
    logger.info(f"Available properties in the HDF5 file:\n{log_properties}")

    
    # Get the energy logged via PropertiesStream
    energies_calculator = data.get_property(properties.energy, atomistic=False)
    # Get potential energies stored in the MD system
    energies_system = data.get_potential_energy()

    # Check the overall shape
    logger.debug(f"Shape: {energies_system.shape}")
    logger.debug(f"data.entries: {data.entries}")
    logger.debug(f"data.time_step (in atomic units): {data.time_step}")


    # Convert the system potential energy from internal units (kJ/mol) to Hartree
    energies_system *= spk_units.convert_units("kJ/mol", "Hartree")

    # Plot the energies
    #plot_energies_system_vs_calculator(data, energies_system, energies_calculator)
    logger.debug(f"Min energy: {np.min(energies_system)} Hartree")
    logger.debug(f"Max energy: {np.max(energies_system)} Hartree")
    
    
    ####################### 2) Prepare Data and Paths #########################
    data_prefix = set_data_prefix()
    model_path = cfg.globals.model_path
    md_workdir = cfg.run.path

    split_file = os.path.join(data_prefix, "splits", trajectory_dir, "inner_splits_0.npz")
    if not os.path.exists(split_file):
        raise FileNotFoundError(f"Missing split file: {split_file}")
    path_to_db = os.path.join(data_prefix, trajectory_dir, "md_trajectory.db")
    logger.debug(f"Path to database: {path_to_db}")

    datamodule = load_xtb_dataset(
        db_path=path_to_db,
        num_workers=cfg.data.num_workers,
        batch_size=cfg.data.batch_size,
        split_file=split_file
    )
    # Plot energies of the actual testdata
    test_data = datamodule.test_dataset
    test_energies = []
    for i, d in enumerate(test_data):
        if i >= 200:
            break
        test_energies.append(d["energy"])
    test_energies = np.array(test_energies)
    plot_energies(data, test_energies, energies_system)
    exit()

    
    # Plot the temperature
    plot_temperature(data)
    logger.debug(f"Min temperature: {np.min(data.get_temperature())} K")
    logger.debug(f"Max temperature: {np.max(data.get_temperature())} K")

    # extract structure information from HDF5 data
    trajectory_path = os.path.join(md_workdir, "trajectory.xyz")
    if not os.path.exists(trajectory_path):
        md_atoms = data.convert_to_atoms()

        # write list of Atoms to XYZ file
        write(
            trajectory_path,
            md_atoms,
            format="xyz"
        )

    # Initialize the spectrum
    equilibrated_data = HDF5Loader(log_file, skip_initial=10000) # i.e. skip first half
    spectrum = PowerSpectrum(equilibrated_data, resolution=2048)

    # Compute the spectrum for the first molecule (default)
    spectrum.compute_spectrum(molecule_idx=0)

    # Get frequencies and intensities
    frequencies, intensities = spectrum.get_spectrum()

    plot_spectrum(frequencies, intensities)

    



if __name__ == "__main__":
    args = parse_args()
    main(**args)