name: schnet
channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.12
  - pip=25.0

  - pip:
      - schnetpack==2.1.1 
      - seaborn==0.13.2
      - statsmodels==0.14.4
      - git+https://github.com/Quantum-Accelerators/xtb_ase.git
      - fastatomstruct==1.4.2

  # other dependencies
  - xtb=6.6.0
  - plotly=6.1.1
  - mdanalysis=2.9.0
  - ipykernel=6.29.5 # for jupyter lab in vs code

  # handled by schnetpack:
  # - pytorch>=2.5.0
  # - pytorch-lightning>=2.0.0
  # - numpy>=2.0.0
  # - hydra-core>=1.1.0
  # - ase>=3.21
  