import argparse
import os
import numpy as np
import matplotlib.pyplot as plt

from md_with_schnet.setup_logger import setup_logger
from md_with_schnet.utils import set_plotting_config, set_data_prefix


logger = setup_logger(logging_level_str="debug")

# Script to generate plots comparing the different energies (potential etc.).
# Example command to run the script from within code directory:
"""
python -m md_with_schnet.data_analysis.XTB.plot_energies --trajectory_dir MOTOR_MD_XTB/T300_1 --show_plots
"""


def parse_args() -> dict:
    """ 
    Parse command-line arguments. 
    Returns:
        dict: Dictionary containing command-line arguments.
    """
    parser = argparse.ArgumentParser(description="Plotting script for XTB datasets")
    parser.add_argument("--trajectory_dir", type=str, default="MOTOR_MD_XTB/T300_1", help="Directory containing the trajectory data generated by Turbomole (default: MOTOR_MD_XTB/T300_1)")
    parser.add_argument("--show_plots", action="store_true", help="Show plots before saving them (default: False)")
    return vars(parser.parse_args())


def main(trajectory_dir: str, show_plots: bool):
    # setup
    plot_dir = os.path.expanduser('~/whk/code/md_with_schnet/data_analysis/plots')
    data_prefix = os.path.join(set_data_prefix(), trajectory_dir)
    plot_path = os.path.join(plot_dir, f"XTB/kinetic_energy_and_temperature.pdf")
    path = os.path.join(data_prefix, 'energies.txt')

    all_energies = np.loadtxt(path, usecols=(1, 5)) # 1 E_kin, 2 E_tot, 3 E_pot, 5 T
    logger.debug(f'all_energies.shape: {all_energies.shape}')
    nr_of_configs = 200
    first_config = 0
    all_energies = all_energies[first_config:first_config+nr_of_configs]

    # plot kinetic energy and temperature with dual y-axis
    set_plotting_config(fontsize=10, aspect_ratio=1.618, width_fraction=1.0, text_usetex=True)
    fig, ax1 = plt.subplots()
    ax2 = ax1.twinx()
    x_values = np.arange(all_energies.shape[0])
    ax1.plot(x_values, all_energies[:, 0], 'g-')
    ax2.plot(x_values, all_energies[:, 1], 'b-')
    ax1.set_xlabel('Configurations')
    ax1.set_ylabel('Kinetic Energy (au)', color='g')
    ax2.set_ylabel('Temperature (K)', color='b')
    ax1.tick_params(axis='y', labelcolor='g')
    ax2.tick_params(axis='y', labelcolor='b')
    plt.title('Kinetic Energy and Temperature over Time')
    plt.tight_layout()
    
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')
    logger.info(f"Saved plot to: {plot_path}")
    if show_plots:
        plt.show()
    plt.close()

    
    


if __name__=="__main__":
    args = parse_args()
    main(**args)